aprsd.py

This patch adds the standard python main() and
the requisite test for the script name.

Added standard python main()

---

aprsd.py

This patch adds the cli options for setting the host, password
and the base callsign

Added password, callsign and host

---

aprsd/main.py
aprsd/utils.py

This patch completes the migration to using a config.yml file.
~/.aprsd/config.yml is now required and all options for callsign,
imap, aprs user, passwords are in the config.  If there is no existing
~/.aprsd/config.yml file, then the app will output a sample config
and exit.
This patch also adds a global logging facility that allows logging all
commands to aprsd.log as well as stdout.  You can disable logging to
stdout by adding --quiet on the command line.  You can specify the log
level with --loglevel INFO.  By default the log level is DEBUG.
This patch also updates some formatting issues and small refactoring
to ensure that the logging facility and config is read prior to starting
any network connections and/or services.

Require ~/.aprsd/config.yml

---

aprsd/fake_aprs.py
aprsd/fuzzyclock.py
aprsd/main.py
aprsd/utils.py
requirements.txt
setup.cfg
tox.ini

This introduced the six lib which can translate common
py2 vs py3 incompatibilities.
https://six.readthedocs.io/

Fixed all pep8 errors and some py3 errors

---

.github/workflows/python.yml
Dockerfile
aprsd/main.py
build/bin/run.sh
build/build.sh
docker-compose.yml

This patch refactors the socket management
to use select, as well as refactor all of the
commands into a COMMAND_ENVELOPE dictionary.
this patch also adds the Dockerfile for building a container image for aprsd.
This also includes a sample docker-compose.yml file for setting up and launching the container.

Refactor networking and commands

---

Dockerfile-dev
build/bin/run.sh
docker-compose.yml

This patch updates the Dockerfile for building the official container
image and includes the ability to load external pypi modules as plugins
at container startup.

Updates for building containers

---

README.rst

This patch updates the README.rst to include an index table at the top
as well as a section describing building and using the docker container

Updated README with a TOC

---

.github/workflows/python.yml
aprsd/client.py
aprsd/email.py
aprsd/main.py
aprsd/messaging.py
aprsd/plugin.py
aprsd/utils.py
dev-requirements.in
dev-requirements.txt
requirements.in
requirements.txt
test-requirements-py2.txt
test-requirements.txt
tests/test_main.py
tox.ini

This branch refactors the majority of main.py out into individual
modules to compartmentalize the code.  Migrated all email related
features unti email.py, sending of messages into messaging.py
Also refactored all of the socket code to use aprslib for all APRS-IS
communication as well as message/packet processing.
Moved the email command into it's own Plugin.

Major refactor

---

aprsd/plugin.py

backout my patch that broke tox, trying to push to craiger-test branch

---

Makefile

This patch adds a Makefile for helping setup a dev environment
as well as running tox tests for those that aren't used to python
development.

Added Makefile for easy dev setup

---

INSTALL.txt
aprsd/dev.py
aprsd/plugin.py
aprsd/plugins/weather.py
setup.cfg

This patch adds a new CLI app called aprsd-dev.  arpsd-dev is
used specifically for developing plugins.  It allows you to run a
plugin directly without the need to run aprsd server.
This patch also adds the Weather Metar plugin called WxPlugin.
You can use it to fetch METAR from the nearest station for a callsign
or from a known METAR station id.  Call WxPlugin with a message of
'wx' for closest metar station or 'wx KAUN' for metar at KAUN wx station

Added aprsd-dev plugin test cli and WxPlugin

---

Dockerfile-dev
aprsd/plugin.py
aprsd/plugin_utils.py
aprsd/plugins/location.py
aprsd/plugins/weather.py
aprsd/utils.py
docs/apidoc/aprsd.rst

This patch adds the openweathermap weather plugin.
Also adds a new config option to set the overall
units setting from imperial (default) to metric.
to change it add the following to the ~/.config/aprsd/aprsd.yaml
...
aprsd:
units: metric

Added openweathermap weather plugin

---

aprsd/email.py
aprsd/main.py
aprsd/plugins/location.py
aprsd/plugins/time.py
aprsd/plugins/weather.py
aprsd/utils.py
tests/test_email.py

This patch reorganizes the config file layout and options
to make more logical sense as well as make it more readable.
This breaks backwards compatibility.

Reworked the config file and options

---

README.rst
aprsd-lnav.json
aprsd/client.py
aprsd/flask.py
aprsd/healthcheck.py
aprsd/main.py
aprsd/stats.py
aprsd/threads.py
aprsd/utils.py
aprsd/web/templates/index.html

This patch adds an index page for the flask web server that users
can hit at /
Working on adding graphs of the data.

Added aprsd web index page

---

aprsd/flask.py
aprsd/messaging.py
aprsd/packets.py
aprsd/threads.py
aprsd/web/static/css/index.css
aprsd/web/static/css/tabs.css
aprsd/web/static/js/charts.js
aprsd/web/static/js/tabs.js
aprsd/web/templates/index.html

This patch updates the admin UI to include 3 tabs
of content.
Charts
messages
config
The charts tab is the existing line charts.
The messages tab shows a list of RX (green) and TX (red) messages
from/to aprsd.
The config tab shows the config loaded at startup time.

Add admin UI tabs for charts, messages, config

---

README.rst
aprsd/flask.py
aprsd/packets.py
aprsd/plugin.py
aprsd/plugins/notify.py
aprsd/stats.py
aprsd/threads.py
aprsd/utils.py
aprsd/web/static/js/charts.js

This patch updates the notification thread to send all packets
through the notification plugins.   The plugins themselves need to
do smart filter to not reply to every packet.  This allows for
more interesting plugins.
Also fixed an issue with the messages tab in the admin ui, not
showing all of the recieved packets.   The messages tab now also
sees all the packets that aprsd recieves.

Reworked the notification threads and admin ui.

---

aprsd/threads.py

This patch adds the ability for plugins to send multiple messages
back in response to a command/message.  The plugin simple needs
to return a list of messages (Strings).  Each string in that list
will result in a separate message being sent back to the originator
of the message.

Enable multiple replies for plugins

---

ChangeLog
aprsd/cmds/dev.py
aprsd/config.py
aprsd/log.py
aprsd/logging/logging.py
aprsd/utils.py
requirements.in
requirements.txt

Added python rich library based logging.
The python rich library is extensive and has a really nice
log format that is easier to read and has built in formatting
and coloring of the log output.
To enable rich logging add rich_logging: True in the config file.

Rich logging

---

ChangeLog
aprsd/cmds/completion.py
aprsd/cmds/dev.py
aprsd/cmds/healthcheck.py
aprsd/cmds/list_plugins.py
aprsd/cmds/listen.py
aprsd/cmds/send_message.py
aprsd/cmds/server.py
requirements.in
requirements.txt

This patch updates the ouput of the list-plugins command.
This also adds the ability to show the available plugins
to install that are published packages on pypi.org.
This also shows the list of installed packages from pypi.org
An example of the output:
```
└─> aprsd list-plugins
🐍 APRSD Built-in Plugins 🐍
┏━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Plugin Name            ┃ Info                                                       ┃ Type         ┃ Plugin Path                               ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ EmailPlugin            │ Send and Receive email …
```

Added new feature to list-plugins command

---

aprsd/cmds/healthcheck.py
aprsd/cmds/list_plugins.py
aprsd/cmds/listen.py
aprsd/flask.py
aprsd/log.py
aprsd/messaging.py

This patch updates the logging facility to ensure that
logging to a file works even when --quiet mode is selected.
Also update the listen and list-plugins command to show
a console.status line while waiting for results to come in.

Unify the logging to file and stdout

---

aprsd/client.py

This patch fixes a small bug when both KISS interfaces are disabled.

Fixed an KISS config disabled issue

---

README.rst

This is a small PR to fix some formatting issues in the README file.

README formatting fixes

---

requirements.txt

Bump dependencies to fix python 3.10

---

README.rst

It took me a bit of guesswork to get the project running in Docker so I've updated the README to clarify some of the confusion I had. Hopefully this is helpful to anyone else running it in Docker.

Update docs on using Docker

---

Makefile
aprsd/cmds/server.py
aprsd/cmds/webchat.py
aprsd/threads/rx.py
aprsd/web/chat/static/js/gps.js
aprsd/web/chat/static/js/send-message-mobile.js
aprsd/web/chat/static/js/send-message.js
aprsd/web/chat/templates/index.html
aprsd/web/chat/templates/mobile.html
dev-requirements.txt
requirements.in
requirements.txt

This patch adds initial support for changing the UI for webchat based if the browser is on a mobile device.

Add support for mobile browsers for webchat

---

aprsd/packets/core.py
aprsd/threads/rx.py

This patch adds support for receiving reject messages.

Add support for Reject messages.

---

docker/Dockerfile

This updates the main Dockerfile to be the same as the Dockerfile-dev other than using the official pypi package for aprsd.

Update the Dockerfile

---

INSTALL.txt

The name of the config files has changed, update INSTALL with the new names.

Update INSTALL with new conf files

---

aprsd/conf/plugin_common.py
aprsd/plugin_utils.py
aprsd/plugins/location.py
aprsd/plugins/weather.py

This Patch updates the location plugin to allow configuring which geopy library's supported geocoders.  This patch also adds a fake geopy geocoder class that uses the us government's API for location.

Rework Location Plugin

---

aprsd/client.py
aprsd/clients/kiss.py
aprsd/threads/aprsd.py
aprsd/threads/rx.py

This adds a layer between the client object and the actual client instance, so we can reset the actual client object instance upon failure of connection.

Update client.py to add consumer in the API.

---

aprsd/cmds/admin.py
aprsd/cmds/listen.py
aprsd/stats/collector.py
aprsd/threads/tx.py
aprsd/wsgi.py
requirements.txt

Update the listen command to collect stats as well

Walt listen test

---

aprsd/cmds/fetch_stats.py
aprsd/packets/core.py
aprsd/plugins/fortune.py
aprsd/plugins/location.py
tests/client/test_aprsis.py
tests/client/test_client_base.py
tests/client/test_factory.py
tests/test_main.py

This patch adds a unit test for the APRSClient base class.

Added unit test for client base
