craigerl/aprsd

README.md
aprsd/main.py
aprsd/utils.py
requirements.txt

This patch adds support to read a ~/.aprsd/config.yml file.
If one doesn't exist, it puts out an example yaml string to stdout
that can be copied into a file and edited.
Since this patch adds a new external requirement (pyyaml) you need
to re-install the app for dev with
pip install -e .

Added reading of a config file

---

aprsd/main.py
aprsd/utils.py

This patch adds the port to the aprs: section of the config.yml
as well as fixes a possible issue with the user telnet auth command
where the user is a string and the port is an int.  python can't
concatonate a string with an int.

Added port and fixed telnet user

---

aprsd/main.py
aprsd/utils.py

This patch reads the SMTP settings from the config.yml now.
Also added a logfile entry to the aprs: section of the config.yml
so the logfile can be placed anywhere.

Fixed SMTP settings

---

aprsd/main.py
aprsd/plugin.py
aprsd/utils.py
docker-compose.yml
examples/plugins/example_plugin.py
requirements.txt
tox.ini

This patch adds the new APRSD Command Plugin architecture.
All Comand plugins must implement the same object API, which includes
plugin object is subclass of APRSDPluginBase
version attribute
command_regex attribute
command method
When an APRS command is detected, then the regex is run against
the command.  If the command_regex matches, then the plugin's
command() method will be called.   If the command() method returns
a string, then that string is sent as a reply to the APRS caller.
A new aprs.yml config section is added to support selecting
which plugins to enable.
If you want all plugins enabled, then omit "enabled_plugins" entirely
from the aprs section of the config.
To load custom plugins:
1) create a directory with an `__init__.py` file
2) Add a plugin.py file that contains your …

Created plugin.py for Command Plugins

---

aprsd/main.py
aprsd/plugin.py
examples/plugins/example_plugin.py

This patch fixes the Usage string for a call message
that isn't matched by any plugin.
Plugin object now must impleent a 'command_name' attribute
that is the usage string for that plugin.

Fixed the usage string after plugins introduced

---

aprsd/plugin.py

This patch removes the call to dirname in the search path for plugins. 
It was failing for short paths.

Don't use the dirname for the plugin path search

---

aprsd/main.py

Some emails that had an unknown character set.  when that happens
we can't decode the body of the message properly, so the default body
string was being used, and was attempting to be decoded.  Only byte
strings can be decoded, so the default string is now labeled as a byte
encoding.

Fix unknown characterset emails

---

Dockerfile
Dockerfile-dev

The ubuntu images were running about 533MB in size, so
I refactored the Dockerfiles to use alpine linux, and they run
about 130MB.

Updated the Dockerfile to use alpine

---

aprsd/plugins/time.py
dev-requirements.txt
requirements.in
requirements.txt
tests/test_plugin.py

The existing time plugin had a hard coded PDT for pacific timezone,
when it wasn't.   This patch adds some real timezone conversion from
utc to the tz of the running aprsd server.   This will eventually allow
us to use either the tz of the running aprsd and/or the tz of the
calling callsign if we can just get the tz string from the location
beacon of the caller's callsign.

Fixed TimePlugin timezone issue

---

aprsd/main.py
aprsd/plugins/email.py

The config file defaults to email being off now.  This requires
the user to set the email settings anyway, so the default is off.

Allow email to be disabled.

---

aprsd/healthcheck.py
setup.cfg

This patch adds the healthcheck app that uses the flask stats url
to fetch the internal stats of a running aprsd server.  If the server is
up the stats will return and be checked for 'healthy' status.
IF the url fails to return, healthcheck will exit with -1.  You can use
this script to restart aprsd if healthcheck exits with -1 status.
There is a check against the email thread.  The email thread updates a
deadman's timer every 5 seconds.   If that time gets older than 5
minutes, then healthcheck will say that's a failure and exit with -1.
You can call healthcheck and restart aprsd if it fails (exit -1)

Added healthcheck app

---

README.rst
aprsd/main.py
aprsd/threads.py
aprsd/utils.py
dev-requirements.txt
requirements.in
requirements.txt

This patch adds usage of update_checker to check to make sure the
version of APRSD being launched is the latest version.  Also added a
call to upate_checker as part of the KeepAlive thread.  It will
call update_check every hour.  If there is no aprsd connectivitity,
the update check will silently fail.

Added aprsd version checking

---

aprsd/main.py
aprsd/utils.py

This patch adds the dumping out of a flattened config to the log
at startup.  This is helpful for seeing what aprsd server is actually
using for config entries at startup and since it's in the log, you can
reference it.
```
[07/05/2021 10:59:21 AM] [MainThread  ] [INFO ] Using CONFIG values: - [/Users/i530566/devel/mine/aprsd/aprsd/main.py:465]
[07/05/2021 10:59:21 AM] [MainThread  ] [INFO ] ham.callsign = KO4KWC - [/Users/i530566/devel/mine/aprsd/aprsd/main.py:470]
[07/05/2021 10:59:21 AM] [MainThread  ] [INFO ] aprs.login = KO4KWC-13 - [/Users/i530566/devel/mine/aprsd/aprsd/main.py:470]
[07/05/2021 10:59:21 AM] [MainThread  ] [INFO ] aprs.password = XXXXXXXXXXXXXXXXXXX - [/Users/i530566/devel/mine/aprsd/aprsd/main.py:468]
[07/05/2021 10:59:21 AM] [MainThread  ] [INFO ] aprs.host = …
```

Dump out the config during startup

---

aprsd/client.py
aprsd/flask.py
aprsd/listen.py
aprsd/messaging.py
aprsd/packets.py
aprsd/plugin.py
aprsd/plugins/email.py
aprsd/plugins/fortune.py
aprsd/plugins/location.py
aprsd/plugins/notify.py
aprsd/plugins/ping.py
aprsd/plugins/query.py
aprsd/plugins/stock.py
aprsd/plugins/time.py
aprsd/plugins/version.py
aprsd/plugins/weather.py
aprsd/stats.py
aprsd/threads.py
aprsd/utils.py
aprsd/web/static/js/charts.js
aprsd/web/templates/index.html
setup.cfg
tests/test_plugin.py

Add new watchlist feature
This patch adds a new optional feature called Watch list.
Aprsd will filter IN all aprs packets from a list of callsigns.
APRSD will keep track of the last time a callsign has been seen.
When the configured timeout value has been reached, the next time
a callsign is seen, APRSD will send the next packet from that callsign
through the new notification plugins list.
The new BaseNotifyPlugin is the default core APRSD notify based plugin.
When it gets a packet it will construct a reply message to be sent
to the configured alert callsign to alert them that the seen callsign
is now on the APRS network.
This basically acts as a notification that your watched callsign list is
available on APRS.
The new configuration options:
aprsd:
watch_list:
alert_callsign: NOCALL …

Refactor the plugin interface and manager

---

docker/bin/run.sh
docker/docker-compose.yml

Added a LOG_LEVEL env variable to the docker run.sh file. If you set the LOG_LEVEL env variable to CRITICAL|ERROR|WARNING|INFO, it will set it to one of those. If not it will default to DEBUG. 
I also added the LOG_LEVEL in the docker_compose.yml file as ERROR level. 
Cheers!
Emre

Added LOG_LEVEL env variable for the docker

---

docker/docker-compose.yml

The current docker-compose.yml does not forward port 8001 to allow access to the web interface. This PR updates the docker-compose.yml file to allow access.

Allow web interface when running in Docker

---

docker/docker-compose.yml

Currently the environment variable in the `docker-compose.yml` file does not match the name of the environment variable that `docker/bin/run.sh` expects for installing plugins. Because of this, plugins passed in with the `APRS_PLUGINS` environment variable with docker-compose will not be installed by `docker/bin/run.sh`.
This PR changes the environment variable in the `docker-compose.yml` file from `APRS_PLUGINS` to `APRSD_PLUGINS`. Plugin names passed in via this environment variable are now installed as expected.

Fix plugins not installing via docker-compose

---

aprsd/cmds/list_plugins.py

This PR fixes Issue #92. It appears that the format of the data from PyPI has changed. There is no longer a `released` field, but there is a `created` field. This PR simply replaces the `released` field with the `created` field.

Fix #92 (PyPI scraping)

---

aprsd/clients/kiss.py
aprsd/cmds/webchat.py
aprsd/web/chat/static/js/send-message.js
aprsd/web/chat/templates/index.html
docker/Dockerfile

This patchset allow getting the GPS coordinates from the browser's
geolocation API (which can be denied by user), then send's the GPS
coordinates to aprsd via socketio and then aprsd sends a beacon.
This allows the APRS network to know the location of the person running
the webchat app via browser so packets can get routed back to it.

Send GPS Beacon from webchat interface

---

aprsd/client.py
aprsd/clients/aprsis.py
aprsd/clients/kiss.py
aprsd/conf/common.py
aprsd/rpc/server.py
aprsd/stats.py
aprsd/threads/aprsd.py
aprsd/threads/keep_alive.py
aprsd/threads/rx.py
aprsd/threads/tx.py
dev-requirements.txt
requirements.in
requirements.txt

This patch adds basic ratelimiting to sending out AckPackets and non AckPackets.  This provides a basic way to prevent aprsd from sending out packets as fast as possible, which isn't great for a bandwidth limited network.
This patch also adds some keepalive checks to all threads in the threadslist as well as the network client objects (apris, kiss)

Add ratelimiting for acks and other packets

---

aprsd/rpc/client.py
aprsd/web/admin/templates/index.html
aprsd/wsgi.py
dev-requirements.txt
docker/bin/admin.sh
requirements.in
requirements.txt

This patch starts the work to replace flask-socketio with python-socketio so that uwsgi can be used instead of gunicorn. uwsgi can support websockets.
Have to rework webchat command next

replacement of flask-socketio with python-socketio

---

aprsd/clients/kiss.py
aprsd/packets/core.py
aprsd/stats.py

The KISS client sends the path as part of the headers, so we had to strip out the path from the payload of each message so the path wouldn't get listed twice.

Fix sending packets over KISS interface

---

ChangeLog
aprsd/client.py
aprsd/clients/fake.py
aprsd/cmds/webchat.py
aprsd/conf/client.py
aprsd/packets/__init__.py
aprsd/packets/core.py
aprsd/packets/packet_list.py
aprsd/packets/tracker.py
aprsd/threads/rx.py
aprsd/utils/counter.py
aprsd/web/chat/static/js/send-message.js

Sometimes over KISS clients (RF), we can get duplicate packets due to having many digipeters in range of the TNC that aprsd is
connected to.   We will now filter out any dupe packets that aprsd
is still in the process of doing it's 3 acks.

Fix for dupe packets.

---

aprsd/cmds/listen.py

The click block specifies aprs-login but the error indicated aprs_login

Normalize listen --aprs-login

---

aprsd/cmds/webchat.py
aprsd/web/chat/static/js/send-message.js
aprsd/web/chat/templates/index.html

This patch adds the new feature of trying to fetch the location distance and bearing for each callsign in the webchat tabs. This is handy when out on the go, you can get a general idea where the other callsign is when chatting with them.
First aprsd webchat tries to fetch the location with aprs.fi REST api call.  This assumes internet access.  If this fails, then webchat will send a special message to REPEAT to ask it for
the location information for the callsign.   This will send over
the air.

Added location for callsign tabs in webchat

---

.gitignore
aprsd/cmds/listen.py
aprsd/cmds/server.py
aprsd/packets/__init__.py
aprsd/packets/core.py
aprsd/packets/filter.py
aprsd/packets/filters/dupe_filter.py
aprsd/packets/filters/packet_type.py
aprsd/threads/__init__.py
aprsd/threads/rx.py
aprsd/utils/objectstore.py

This patch adds the new PacketFilter class as a generic mechanism for doing packet filtering during the packet processing phase of recieving packets.
The packet phases are:
1. reception and stats collection
2. packet processing.
Each phase has a single thread for handling that phase.
Phase 1:
The ARPSDRXThread connects to the APRS client, and gets packets from the client.  Then it puts the packet through the Collector for stats and tracking.  Then the packet is put into the packet_queue.
Phase 2:
Packets are pulled from the packet_queue.  Then packets are run through the PacketFilter mechanism, then processed depending on the command being run.
By default there is 1 loaded packet filter, which is the DupePacketFilter which removes "duplicate" packets that aprsd has already seen and …

Added new PacketFilter mechanism
